/*
 * AfficheMess.java
 *
 * Created on 16 f�vrier 2006, 23:46
 */

package lottaur.webmail;

import lottaur.Moteur.MessageLotTaur;
import lottaur.Moteur.SaveFic;
import com.sun.mail.util.BASE64DecoderStream;
import java.io.File;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Part;
import javax.mail.internet.MimeMultipart;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.ListSelectionModel;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLFrameHyperlinkEvent;
import lottaur.webmail.model.listeFicModel;

/**
 *
 * @author  christophe
 */
public class AfficheMess extends javax.swing.JPanel {
    private MessageLotTaur test=null;
    private listeFicModel modelLstFic=null;
    private int _numeroMess=-1;
    /** Creates new form AfficheMess */
    public AfficheMess() {
        modelLstFic = new listeFicModel();
        initComponents();
        btnHtml.setVisible(false);
        btnText.setVisible(false);
    }
    
     private HyperlinkListener createHyperLinkListener()
     {
        return new HyperlinkListener(){
            public void hyperlinkUpdate(HyperlinkEvent e){
            if ( e.getEventType() == HyperlinkEvent.EventType.ACTIVATED ){
                 if (e instanceof HTMLFrameHyperlinkEvent){
                     ((HTMLDocument) EditorHtml.getDocument())
                             .processHTMLFrameHyperlinkEvent(
                         (HTMLFrameHyperlinkEvent) e);
                 }else{
                    try{
                        // path = e.getURL().getPath();
                        // EditorHtml.setPage( e.getURL() );
                        //il faut ouvrir l'�diteur html par d�fault'
                     }catch (Exception ioe){
                         System.out.println("IOE: " + ioe);
                     }
                 }
             }
         }
        };
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        EditorHtml = new javax.swing.JEditorPane();
        panelBouton = new javax.swing.JPanel();
        btnText = new javax.swing.JButton();
        btnHtml = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstFichier = new javax.swing.JList();

        EditorHtml.setEditable(false);
        jScrollPane1.setViewportView(EditorHtml);

        org.jdesktop.layout.GroupLayout panelBoutonLayout = new org.jdesktop.layout.GroupLayout(panelBouton);
        panelBouton.setLayout(panelBoutonLayout);
        panelBoutonLayout.setHorizontalGroup(
            panelBoutonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 354, Short.MAX_VALUE)
        );
        panelBoutonLayout.setVerticalGroup(
            panelBoutonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 48, Short.MAX_VALUE)
        );

        btnText.setText("Text");
        btnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click(evt);
            }
        });

        btnHtml.setText("Html");
        btnHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click(evt);
            }
        });

        jLstFichier.setFont(new java.awt.Font("Dialog", 0, 12));
        jLstFichier.setModel(modelLstFic);
        jLstFichier.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLstFichier.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jLstFichier.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLstFichierValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(jLstFichier);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(btnHtml)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnText)
                .add(17, 17, 17)
                .add(panelBouton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelBouton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnHtml)
                            .add(btnText))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLstFichierValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLstFichierValueChanged
// TODO add your handling code here:
         if( !evt.getValueIsAdjusting() ){
           SaveFic fic = (SaveFic) jLstFichier.getSelectedValue();
           JFileChooser testFic = new JFileChooser();
           try{
               File nomtemp = new File(fic.getName());
               testFic.setSelectedFile(nomtemp);
               testFic.showSaveDialog(this);
               File nomfic = testFic.getSelectedFile();
                try {
                    fic.saveFile(nomfic);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
           }catch(IOException ex){
                ex.printStackTrace();
           }
         }
    }//GEN-LAST:event_jLstFichierValueChanged

    private void click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_click
        if(evt.getSource() == btnText ){
            EditorHtml.setContentType(test.getContentTypeText());
            EditorHtml.setText(test.getStrText());
        }else if(evt.getSource() == btnHtml ){
            EditorHtml.setContentType(test.getContentTypeHtml());
            EditorHtml.setText(test.getStrHtml());
        }
    }//GEN-LAST:event_click

    void setMessage(MessageLotTaur msg) {
        test = msg;
        String content = test.getContentTypeDefault();
        if( content==null )
            content = "text/plain; charset=ISO-8859-1";
        System.out.println(content);
        EditorHtml.setContentType(content);
        EditorHtml.setText(test.getStrDefault());
        btnHtml.setVisible(test.isAlternative());
        btnText.setVisible(test.isAlternative());
        boolean bAvecFichierAttach = test.AvecFichierAttach();
        jLstFichier.setVisible(bAvecFichierAttach);
        if( bAvecFichierAttach ){
            modelLstFic.setList(test.getList());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane EditorHtml;
    private javax.swing.JButton btnHtml;
    private javax.swing.JButton btnText;
    private javax.swing.JList jLstFichier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBouton;
    // End of variables declaration//GEN-END:variables
    
}
