/*
 * ListeFolder.java
 *
 * Created on 13 f�vrier 2006, 13:54
 */

package lottaur.webmail;
import lottaur.Moteur.ListeMsgLotTaur;
import lottaur.Moteur.MessageLotTaur;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import lottaur.webmail.model.listeMsgModel;

/**
 *
 * @author  CRivier
 */
public class ListeFolder extends javax.swing.JPanel{
    
    protected listeMsgModel model;
    protected ListeMsgLotTaur _lst;
    protected JFrame _owner=null;
    
    /** Creates new form ListeFolder */
    public ListeFolder( JFrame owner, ListeMsgLotTaur lst ) {
        super();
        _owner = owner;
        _lst = lst;
        model = new listeMsgModel();
        initComponents();
        try{
            model.setListeMsg(_lst);
        }catch(Exception ex){
            ex.printStackTrace();
        }
        // find out what is pressed
	ListeMessage.getSelectionModel().addListSelectionListener(
	    new FolderPressed());
        ListeMessage.addMouseListener(
                new MouseListener(){
                public void mouseClicked(MouseEvent e) {
                    if( e.getButton()==3 ){
                        //cr�ation d'une popup
                        popupMessage.show(ListeMessage,e.getX(),e.getY());
                    }
                        
                }

                public void mousePressed(MouseEvent e) {
                }

                public void mouseReleased(MouseEvent e) {
                }

                public void mouseEntered(MouseEvent e) {
                }

                public void mouseExited(MouseEvent e) {
                }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        popupMessage = new javax.swing.JPopupMenu();
        supprime = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeMessage = new javax.swing.JTable();

        supprime.setText("Suppression Message");
        supprime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimeActionPerformed(evt);
            }
        });

        popupMessage.add(supprime);

        ListeMessage.setModel(model          );
        jScrollPane1.setViewportView(ListeMessage);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimeActionPerformed
// TODO add your handling code here:
        //Suppression du message s�lectionn�
       
    }//GEN-LAST:event_supprimeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListeMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popupMessage;
    private javax.swing.JMenuItem supprime;
    // End of variables declaration//GEN-END:variables
   class FolderPressed implements ListSelectionListener {

	public void valueChanged(ListSelectionEvent e) {
	    if (model != null && !e.getValueIsAdjusting()) {
                ListSelectionModel lm = (ListSelectionModel) e.getSource();
                int which = lm.getMaxSelectionIndex();
                if (which != -1) {
                    MessageLotTaur msg=null;
                    if( _lst.getNbMsg()>which )
                        msg = _lst.getMsg(which);
                    try{
                        if( _owner instanceof WebmailApp ){
                            WebmailApp tmp = (WebmailApp)_owner;
                            tmp.setMessage(msg);
                        }
                    }catch(Exception ex){
                        ex.printStackTrace();
                    }
                }
	    }
	}
    }
}
