/*
 * WebmailApp.java
 *
 * Created on 9 f�vrier 2006, 14:47
 */

package lottaur.webmail;

import lottaur.Moteur.ListeMsgLotTaur;
import lottaur.Moteur.MessageLotTaur;
import lottaur.Moteur.ParamConnect;
import java.awt.Image;
import java.awt.Toolkit;
import javax.mail.Folder;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Store;
import javax.mail.URLName;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.LayoutStyle;

import lottaur.ressources.Ressource;
import lottaur.webmail.model.listeMsgModel;
import lottaur.webmail.presenter.pres_SentMessage;
import lottaur.webmail.presenter.pres_addConnect;

/**
 *
 * @author  CRivier
 */
public class WebmailApp extends javax.swing.JFrame implements java.lang.Runnable{
    
    ListeFolder lstRep;
    listeMsgModel model = new listeMsgModel();
    private AfficheMess mess = new AfficheMess();
    private ListeMsgLotTaur _lst = null;
    private ParamConnect _paramConnect = null;
    /** Creates new form WebmailApp */
    public WebmailApp(ParamConnect para) throws MessagingException{
        _paramConnect = new ParamConnect(para);
        initComponents();
        Init(para);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("FramePrincipale");
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/refresh.png")));
        jToggleButton1.setBorder(null);
        jToggleButton1.setIconTextGap(0);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/add.png")));
        jToggleButton2.setBorder(null);
        jToggleButton2.setIconTextGap(0);
        jToggleButton2.setRolloverEnabled(true);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToggleButton1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addContainerGap(798, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(jToggleButton1)
                .addComponent(jToggleButton2))
        );

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        pres_SentMessage presSent = new pres_SentMessage(this,_paramConnect);
        presSent.CreateView();
        presSent.setVisibleView();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new WebmailApp().setVisible(true);
            }
        });
    }

    public void run(){
        //Init(_paramConnect);
    }
    
    public void Init(ParamConnect para) throws MessagingException{
        Folder repertoire = null;
        Session session = Session.getDefaultInstance(System.getProperties(), null);
        URLName urln = new URLName(para.getStrConnect());
        Store store=null;
        
        try{
        store = session.getStore(urln);
        }catch(Exception ex){ex.printStackTrace();}

        // connect to the Store if we need to
        if (!store.isConnected()) {
            store.connect();
        }

        // get the default folder, 
        repertoire = store.getFolder("INBOX");

         _lst = new ListeMsgLotTaur(repertoire);
    
        try{
            model.setListeMsg(_lst);
        }catch(Exception ex){
            ex.printStackTrace();
        }
        lstRep = new ListeFolder( this, _lst);
            
        JSplitPane jsp = new JSplitPane(JSplitPane.VERTICAL_SPLIT,
				lstRep, mess );
        
        jsp.setBounds(0,0,jPanel2.getWidth(),jPanel2.getHeight());
	jsp.setOneTouchExpandable(true);
        jPanel2.add(jsp);
        
       //Affichage de l'icone
        ImageIcon monIcon = new ImageIcon(Ressource.class.getResource("icone.png"));
        this.setIconImage(monIcon.getImage());
        this.setTitle("LotTaur ("+para.getUser()+":"+para.getServeur()+")");
    }

    void setMessage(MessageLotTaur msg) {
        mess.setMessage(msg);    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
    
}
